format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
comment_width = 100
max_width = 120
imports_layout = "Mixed"
wrap_comments = true
newline_style = "unix"
use_field_init_shorthand = true
use_try_shorthand = true
